### ISSUE TITLE
Option to check a checkbox as a field

### ISSUE THREAD

**Issue by fwarmuth** [branhill/captive-portal-assistant#1]
Hey,
would it be possible to add a function to activate a checkbox during fill in?
My situation looks like this:
![image](https://user-images.githubusercontent.com/21278959/60571069-23447680-9d73-11e9-9387-48e381961443.png)

checkbox part of homepage looks like this:
```
...
<label for="accept_termsofuse" class="ewc_s_label"><a href="#" class="ewc_s_tos" onclick="openWindow('disclaimer')">Terms of Use</a></label>
<input type="checkbox" id="voucherLogon-accept_termsofuse" name="accept_termsofuse" value="" class="checkbox ewc_s_checkbox">
<div class="checkbox-label"><label for="voucherLogon-accept_termsofuse" class="ewc_s_label">I agree to the terms of use</label></div>
...
```

regards

**Comment by branhill** [comment]
Sorry for the delay. There was a bug in fill checkbox, now it should works. Just use `accept_termsofuse` as field name and leave value empty in settings.
